### ISSUE TITLE
Use MQTT Discovery to register device sensors with Home Assistant

### ISSUE THREAD

**Issue by danielrheinbay** [thanksmister/voice-panel-android#14]
Using [MQTT Discovery](https://www.home-assistant.io/docs/mqtt/discovery/), Home Assistant can make use of sensors with only minimal configuration needed.
If Voice Panel implements MQTT Discovery, this would greatly reduce manual configuration effort and errors, especially when multiple Voice Panels are used.

# Status quo
Voice Panel can report device sensor data over MQTT (temperature, light, pressure, battery, etc.).
However, each sensor must be configured manually on the Home Assistant site, as described in README:
```
sensor:
 - platform: mqtt
    state_topic: "voicepanel/sensor/temperature"
    name: "Voice Panel Temperature"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.value }}'
```

# To be
Voice Panel uses MQTT Discovery as described in https://www.home-assistant.io/docs/mqtt/discovery/. No manual configuration required for most device sensors, as Home Assistant will discover them automagically.
